name: Testing

on:
  push:
    paths:
      - 'Lecture 7 (Testing, CI and CD)/airline1/**'

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Django
        run: pip3 install --user django

      - name: Run Django unit tests
        run: |
          cd "Lecture 7 (Testing, CI and CD)/airline1"
          python3 manage.py test
